### Алгоритмы интеллектуальной обработки больших объемов данных
## Домашнее задание №3 - Дерево решений


**Общая информация**

**Срок сдачи:** до 30 апреля 2018, 06:00   
**Штраф за опоздание:** -2 балла после 06:00 30 апреля, -4 балла после 06:00 7 мая, -6 баллов после 06:00 14 мая, -8 баллов после 06:00 21 мая

При отправлении ДЗ указывайте фамилию в названии файла   


Присылать ДЗ необходимо в виде ссылки на свой github репозиторий в slack @alkhamush


Используйте данный Ipython Notebook при оформлении домашнего задания.

###### Задание 1 (3 балла)
Разберитесь в коде MyDecisionTreeClassifier, который уже частично реализован. Допишите код там, где написано "Ваш код". Ваша реализация дерева должна работать по точности не хуже DecisionTreeClassifier из sklearn. Точность проверяется на wine и Speed Dating Data.

###### Задание 2 (3 балла)
Добиться скорости работы на fit не медленнее чем в 10 раз sklearn на данных wine и Speed Dating Data. 
Для этого используем numpy.

###### Задание 3 (2 балла)
Добавьте функционал, который определяет значения feature importance. Выведите 10 главных фичей под пунктом Задание 4 (уже написано ниже) для MyDecisionTreeClassifier и DecisionTreeClassifier так, чтобы сразу были видны выводы и по MyDecisionTreeClassifier, и по DecisionTreeClassifier. Используем данные Speed Dating Data.

###### Задание 4 (2 балла)
С помощью GridSearchCV или RandomSearchCV подберите наиболее оптимальные параметры для случайного леса (Выберете 2-3 параметра). Используем данные Speed Dating Data. Задание реализуйте под пунктом Задание 5 (уже написано ниже)


**Штрафные баллы:**

1. Невыполнение PEP8 -1 балл
2. Отсутствие фамилии в имени скрипта (скрипт должен называться по аналогии со stroykova_hw3.ipynb) -1 балл
3. Все строчки должны быть выполнены. Нужно, чтобы output команды можно было увидеть уже в git'е. В противном случае -1 балл
4. При оформлении ДЗ нужно пользоваться данным файлом в качестве шаблона. Не нужно удалять и видоизменять написанный код и текст. В противном случае -1 балл

In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from sklearn.datasets import load_wine
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, f1_score
from sklearn.model_selection import KFold, train_test_split, GridSearchCV, RandomizedSearchCV
from sklearn.tree import DecisionTreeClassifier

%matplotlib inline
%load_ext pycodestyle_magic

In [249]:
np.apply_along_axis(lambda x: 2 * x, 0, np.array([0, 1, 2, 0, 1, 0]))

array([0, 2, 4, 0, 2, 0])

In [314]:
v[:-1]

array([1, 1, 1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5])

In [306]:
v

array([1, 1, 1, 1, 1, 2, 2, 2, 3, 4, 3, 4, 3, 4, 3, 4, 5, 5, 5])

In [315]:
np.where(v[:-1] != v[1:])[0] + 1

array([ 5,  8, 12, 16])

In [375]:
#%%pycodestyle


class MyDecisionTreeClassifier:
    NON_LEAF_TYPE = 0
    LEAF_TYPE = 1

    def __init__(self, min_samples_split=2, max_depth=None, sufficient_share=1.0, criterion='gini', max_features=None):
        self.tree = dict()
        self.min_samples_split = min_samples_split
        self.max_depth = max_depth
        self.sufficient_share = sufficient_share
        self.num_class = -1
        self.feature_importances_ = None
        if criterion == 'gini':
            self.G_function = self.__gini
        elif criterion == 'entropy':
            self.G_function = self.__entropy
        elif criterion == 'misclass':
            self.G_function = self.__misclass
        else:
            print('invalid criterion name')
            raise

        if max_features == 'sqrt':
            self.get_feature_ids = self.__get_feature_ids_sqrt
        elif max_features == 'log2':
            self.get_feature_ids = self.__get_feature_ids_log2
        elif max_features == None:
            self.get_feature_ids = self.__get_feature_ids_N
        else:
            print('invalid max_features name')
            raise

    def __gini(self, l_c, l_s, r_c, r_s):
        l_s = l_s.astype('float')
        r_s = r_s.astype('float')
        return  ((1 - np.sum((np.bincount(l_c) / l_c.shape[0]) ** 2)) * l_c.shape[0] + 
                 (1 - np.sum((np.bincount(r_c) / r_c.shape[0]) ** 2)) * r_c.shape[0]) / (l_c.shape[0] + r_c.shape[0])
    
    def __entropy(self, l_c, l_s, r_c, r_s):
        return # Ваш код в 1 строчку

    def __misclass(self, l_c, l_s, r_c, r_s):
        return # Ваш код в 1 строчку

    def __get_feature_ids_sqrt(self, n_feature):
        feature_ids = np.arange(n_feature)
        np.random.shuffle(feature_ids)
        return feature_ids[: int(np.sqrt(feature_ids.shape[0]))]
        
    def __get_feature_ids_log2(self, n_feature):
        feature_ids = np.arange(n_feature)
        np.random.shuffle(feature_ids)
        return feature_ids[: int(np.log(feature_ids.shape[0]) / np.log(2))]

    def __get_feature_ids_N(self, n_feature):
        return np.arange(n_feature)
    
    def __sort_samples(self, x, y):
        sorted_idx = x.argsort()
        return x[sorted_idx], y[sorted_idx]

    def __div_samples(self, x, y, feature_id, threshold):
        left_mask = x[:, feature_id] > threshold
        right_mask = ~left_mask
        return x[left_mask], x[right_mask], y[left_mask], y[right_mask]

    def __find_threshold(self, x, y):
        feature_ids = self.get_feature_ids(x.shape[1])
        min_gain = 1
        for idx, col in enumerate(x[:, feature_ids].T):
            col, y_sort = self.__sort_samples(col, y)
            for ind in np.where(y_sort[:-1] != y_sort[1:])[0] + 1:
                l_s, r_s = col[:ind], col[ind:]
                l_c, r_c = y_sort[:ind], y_sort[ind:]
                gain = self.G_function(l_c, l_s, r_c, r_s)
                if gain == 0:
                    return idx, col[ind - 1]
                if gain < min_gain:
                    res_idx = idx
                    res_thr = col[ind - 1]
                    min_gain = gain
                        
        return res_idx, res_thr

    def __fit_node(self, x, y, node_id, depth):
        if depth == self.max_depth or self.min_samples_split >= x.shape[0] or len(np.unique(y)) == 1:
            self.tree[node_id] = [self.__class__.LEAF_TYPE, np.argmax(np.bincount(y))]
            return
        feature_id, threshold = self.__find_threshold(x, y)
        self.tree[node_id] = [self.__class__.NON_LEAF_TYPE, feature_id, threshold]
        X_left, X_right, y_left, y_right = self.__div_samples(x, y, feature_id, threshold)
        self.__fit_node(X_left, y_left, 2 * node_id + 1, depth + 1)
        self.__fit_node(X_right, y_right, 2 * node_id + 2, depth + 1)
    
    def fit(self, x, y):
        self.num_class = np.unique(y).size
        self.__fit_node(x, y, 0, 0) 

    def __predict_class(self, x, node_id):
        node = self.tree[node_id]
        if node[0] == self.__class__.NON_LEAF_TYPE:
            _, feature_id, threshold = node
            if x[feature_id] > threshold:
                return self.__predict_class(x, 2 * node_id + 1)
            else:
                return self.__predict_class(x, 2 * node_id + 2)
        else:
            return node[1]

    def __predict_probs(self, x, node_id):
        node = self.tree[node_id]
        if node[0] == self.__class__.NON_LEAF_TYPE:
            _, feature_id, threshold = node
            if x[feature_id] > threshold:
                return self.__predict_probs(x, 2 * node_id + 1)
            else:
                return self.__predict_probs(x, 2 * node_id + 2)
        else:
            return node[2]
        
    def predict(self, X):
        return np.array([self.__predict_class(x, 0) for x in X])
    
    def predict_probs(self, X):
        return np.array([self.__predict_probs(x, 0) for x in X])

    def fit_predict(self, x_train, y_train, predicted_x):
        self.fit(x_train, y_train)
        return self.predict(predicted_x)


In [376]:
my_clf = MyDecisionTreeClassifier(min_samples_split=2)
clf = DecisionTreeClassifier(min_samples_split=2)

In [123]:
wine = load_wine()
X_train, X_test, y_train, y_test = train_test_split(wine.data, wine.target, test_size=0.1, stratify=wine.target)

## Проверка скорости работы на wine

In [371]:
%timeit clf.fit(X_train, y_train)

782 µs ± 9.21 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [ ]:
%timeit my_clf.fit(X_train, y_train)

## Проверка качества работы на wine

In [373]:
f1_score(y_pred=clf.predict(X_test), y_true=y_test, average='macro')

0.83721833721833727

In [374]:
f1_score(y_pred=my_clf.predict(X_test), y_true=y_test, average='macro')

0.88850038850038848

## Подготовка данных Speed Dating Data 

In [14]:
!ls speed-dating-experiment

Speed Dating Data.csv  Speed Dating Data Key.doc


In [20]:
Data = pd.read_csv('speed-dating-experiment/Speed Dating Data.csv', sep=',', encoding="ISO-8859-1")

In [262]:
pd.options.display.max_columns = 200

In [263]:
Data

iid    id  gender  idg  condtn  wave  round  position  positin1  order  \
0       1   1.0       0    1       1     1     10         7       NaN      4   
1       1   1.0       0    1       1     1     10         7       NaN      3   
2       1   1.0       0    1       1     1     10         7       NaN     10   
3       1   1.0       0    1       1     1     10         7       NaN      5   
4       1   1.0       0    1       1     1     10         7       NaN      7   
5       1   1.0       0    1       1     1     10         7       NaN      6   
6       1   1.0       0    1       1     1     10         7       NaN      1   
7       1   1.0       0    1       1     1     10         7       NaN      2   
8       1   1.0       0    1       1     1     10         7       NaN      8   
9       1   1.0       0    1       1     1     10         7       NaN      9   
10      2   2.0       0    3       1     1     10         3       NaN     10   
11      2   2.0       0    3       1     1     10         3       NaN      9   
12      2   2.0       0    3       1     1     10         3       NaN      6   
13      2   2.0       0    3       1     1     10         3       NaN      1   
14      2   2.0       0    3       1     1     10         3       NaN      3   
15      2   2.0       0    3       1     1     10         3       NaN      2   
16      2   2.0       0    3       1     1     10         3       NaN      7   
17      2   2.0       0    3       1     1     10         3       NaN      8   
18      2   2.0       0    3       1     1     10         3       NaN      4   
19      2   2.0       0    3       1     1     10         3       NaN      5   
20      3   3.0       0    5       1     1     10         9       NaN      6   
21      3   3.0       0    5       1     1     10         9       NaN      5   
22      3   3.0       0    5       1     1     10         9       NaN      2   
23      3   3.0       0    5       1     1     10         9       NaN      7   
24      3   3.0       0    5       1     1     10         9       NaN      9   
25      3   3.0       0    5       1     1     10         9       NaN      8   
26      3   3.0       0    5       1     1     10         9       NaN      3   
27      3   3.0       0    5       1     1     10         9       NaN      4   
28      3   3.0       0    5       1     1     10         9       NaN     10   
29      3   3.0       0    5       1     1     10         9       NaN      1   
...   ...   ...     ...  ...     ...   ...    ...       ...       ...    ...   
8348  551  21.0       1   42       2    21     22         5      21.0      7   
8349  551  21.0       1   42       2    21     22        11      21.0     13   
8350  551  21.0       1   42       2    21     22        17      21.0     19   
8351  551  21.0       1   42       2    21     22        14      21.0     16   
8352  551  21.0       1   42       2    21     22        13      21.0     15   
8353  551  21.0       1   42       2    21     22        19      21.0     21   
8354  551  21.0       1   42       2    21     22         3      21.0      5   
8355  551  21.0       1   42       2    21     22         2      21.0      4   
8356  552  22.0       1   44       2    21     22        21      10.0     12   
8357  552  22.0       1   44       2    21     22        12      10.0      3   
8358  552  22.0       1   44       2    21     22        15      10.0      6   
8359  552  22.0       1   44       2    21     22         7      10.0     20   
8360  552  22.0       1   44       2    21     22        22      10.0     13   
8361  552  22.0       1   44       2    21     22        16      10.0      7   
8362  552  22.0       1   44       2    21     22        10      10.0      1   
8363  552  22.0       1   44       2    21     22        18      10.0      9   
8364  552  22.0       1   44       2    21     22         1      10.0     14   
8365  552  22.0       1   44       2    21     22         6      10.0     19   
8366  

In [50]:
[feat for feat in Data if Data[feat].dtype == 'object']

['field',
 'undergra',
 'mn_sat',
 'tuition',
 'from',
 'zipcode',
 'income',
 'career']

## Проверка скорости работы на Speed Dating Data 

In [ ]:
# тут должен быть код типа f1_score(y_pred=clf.predict(X_test), y_true=y_test, average='macro')

In [ ]:
# тут должен быть код типа f1_score(y_pred=my_clf.predict(X_test), y_true=y_test, average='macro')

## Проверка качества работы на Speed Dating Data

In [ ]:
# тут должен быть код типа %time clf.fit(X_train, y_train)

In [ ]:
# тут должен быть код типа %time my_clf.fit(X_train, y_train)

## Задание 3

## Задание 4

## Задание 5